#!/usr/bin/env python3


import argparse
import sys
from asm6502 import asm6502
from pathlib import Path

def get_unique_filename(target_path):
    path = Path(target_path)
    if not path.exists():
        return path

    stem = path.stem
    suffix = path.suffix
    directory = path.parent
    counter = 1

    while True:
        # Tries file(1).txt, file(2).txt, etc.
        new_path = directory / f"{stem}({counter}){suffix}"
        if not new_path.exists():
            return new_path
        counter += 1

parser = argparse.ArgumentParser(
                    prog='6502asm',
                    add_help=True,
                    description='Assembles a 6502 .asm file using py6502',
                    epilog='See https://github.com/dj-on-github/py6502')

parser.add_argument('filename', type=str, nargs='?', help='6502 Assembler source file .asm by default. Omit for stdin')
parser.add_argument('-l', '--list', type=str, dest='listing_filename', help='Filename to send listing output to. Defaults to <filename>.lst')
parser.add_argument('-i', '--intelhex', type=str, dest="ihex_filename", help='Filename to send intelhex output to. Defaults to <filename>.hex')
parser.add_argument('-s', '--symbol', type=str, dest="symbol_filename", help='Filename to send symbol table output to. Defaults to <filename>.sym')
parser.add_argument('-v', '--verbose', action='store_true')

args = parser.parse_args()

using_stdin=False
verbose = (args.verbose==True)

if args.filename:
    filename=args.filename
    f=open(filename,"r")
    using_stdin = False
else:
    f=sys.stdin
    using_stdin=True
    # Usage
    filename = get_unique_filename("output6502.asm")

if using_stdin:
    print("Assembling from stdin")
else:
    print("Assembling from file: filename")

# Get filename without the extension
if using_stdin or (filename==".asm"): # A filename of just .asm would cause a
                                      # zero length prefix.
    filename="output6502.asm"
        
if filename[-4:]=='.asm':
    file_prefix_l = filename[:-4]
else:
    file_prefix_l = filename


if args.listing_filename:
    listing_filename=args.listing_filename
else:
    listing_filename = file_prefix_l+".lst"

listing_file = open(listing_filename,"w")



if args.ihex_filename:
    ihex_filename=args.ihex_filename
else:
    ihex_filename = file_prefix_l+".hex"

ihex_file = open(ihex_filename,"w")



if args.symbol_filename:
    symbol_filename=args.symbol_filename
else:
    symbol_filename = file_prefix_l+".sym"

symbol_file = open(symbol_filename,"w")



verbose = False
if args.verbose:
    verbose = True


lines = f.readlines()

a = asm6502()
(lst,sym) = a.assemble(lines)

# inspect output
for line in lst:
    print(line,file=listing_file)
listing_file.close()
print("Listing writing to: ",listing_filename)

for symbol in sym:
    print(symbol, file=symbol_file)
symbol_file.close()
print("Symbol table written to: ",symbol_filename)

a.print_intelhex(file=ihex_file)
ihex_file.close()
print("Intel Hex object code written to: ",ihex_filename)

if not using_stdin:
    f.close()
