#!/usr/bin/env python

from asm6502 import asm6502

def go(debug=0):  
    lines = list()
    lines.append("    ORG $100")
    lines.append("    ADC #$55	    ")
    lines.append("    ADC $20	        ")
    lines.append("    ADC $20,X	    ")
    lines.append("    ADC $2233	        ")
    lines.append("    ADC $2233,X	    ")
    lines.append("    ADC $2233,Y	    ")
    lines.append("    ADC ($20,X)	    ")
    lines.append("    ADC ($20),Y	    ")
    lines.append("    ADC ($20)	    ")
    lines.append("    AND #$55	    ")
    lines.append("    AND $20	        ")
    lines.append("    AND $20,X	    ")
    lines.append("    AND $2233	        ")
    lines.append("    AND $2233,X	    ")
    lines.append("    AND $2233,Y	    ")
    lines.append("    AND ($20,X)	    ")
    lines.append("    AND ($20),Y	    ")
    lines.append("    AND ($20)	    ")
    lines.append("    ASL A	        ")
    lines.append("    ASL $20	        ")
    lines.append("    ASL $20,X	    ")
    lines.append("    ASL $2233	        ")
    lines.append("    ASL $2233,X	    	    ")
    lines.append("    BCC $55	    ")
    lines.append("    BCS $55	    ")
    lines.append("    BEQ $55	    ")
    lines.append("    BIT #$55	    ")
    lines.append("    BIT $20	    ")
    lines.append("    BIT $20,X	    ")
    lines.append("    BIT $2233	    ")
    lines.append("    BIT $2233,X	    ")
    lines.append("    BMI $55	    ")
    lines.append("    BNE $55	    ")
    lines.append("    BPL $55	    ")
    lines.append("    BRA $55	    ")
    lines.append("    BRK	            ")
    lines.append("    BVC $55	    ")
    lines.append("    BVS $55	    ")
    lines.append("    CLC	            ")
    lines.append("    CLD	            ")
    lines.append("    CLI	            ")
    lines.append("    CLV	            ")
    lines.append("    CMP #$55	    ")
    lines.append("    CMP $20	        ")
    lines.append("    CMP $20	        ")
    lines.append("    CMP $2233	        ")
    lines.append("    CMP $2233,X	    ")
    lines.append("    CMP $2233,Y	    ")
    lines.append("    CMP ($20,X)	    ")
    lines.append("    CMP ($20),Y	    ")
    lines.append("    CMP ($20)	    ")
    lines.append("    CPX #$55	    ")
    lines.append("    CPX $20	        ")
    lines.append("    CPX $2233	        ")
    lines.append("    CPY #$55	    ")
    lines.append("    CPY $20	        ")
    lines.append("    CPY $2233	        ")
    lines.append("    DEA	            ")
    lines.append("    DEC A	            ")
    lines.append("    DEC $20	        ")
    lines.append("    DEC $20,X	    ")
    lines.append("    DEC $2233	        ")
    lines.append("    DEC $2233,X	    ")
    lines.append("    DEX	            ")
    lines.append("    DEY	            ")
    lines.append("    EOR #$55	    ")
    lines.append("    EOR $20	        ")
    lines.append("    EOR $20,X	    ")
    lines.append("    EOR $2233	        ")
    lines.append("    EOR $2233,X	    ")
    lines.append("    EOR $2233,Y	    ")
    lines.append("    EOR ($20,X)	    ")
    lines.append("    EOR ($20),Y	    ")
    lines.append("    EOR ($20)	    ")
    lines.append("    INA")
    lines.append("    INC A	            ")
    lines.append("    INC $20	        ")
    lines.append("    INC $20,X	    ")
    lines.append("    INC $2233	        ")
    lines.append("    INC $2233,X	    ")
    lines.append("    INX	            ")
    lines.append("    INY	            ")
    lines.append("    JMP $2233	        ")
    lines.append("    JMP ($2233)	    ")
    lines.append("    JMP ($2233,X)	    ")
    lines.append("    JSR $2233	        ")
    lines.append("    LDA #$55	    ")
    lines.append("    LDA $20	        ")
    lines.append("    LDA $20,X	    ")
    lines.append("    LDA $2233	        ")
    lines.append("    LDA $2233,X	    ")
    lines.append("    LDA $2233,Y	    ")
    lines.append("    LDA ($20,X)	    ")
    lines.append("    LDA ($20),Y	    ")
    lines.append("    LDA ($20)	    ")
    lines.append("    LDX #$55	    ")
    lines.append("    LDX $20	        ")
    lines.append("    LDX $20,Y	    ")
    lines.append("    LDX $2233	        ")
    lines.append("    LDX $2233,Y	    ")
    lines.append("    LDY #$55	    ")
    lines.append("    LDY $20	        ")
    lines.append("    LDY $20,X	    ")
    lines.append("    LDY $2233	        ")
    lines.append("    LDY $2233,X	    ")
    lines.append("    LSR A	        ")
    lines.append("    LSR $20	        ")
    lines.append("    LSR $20,X	    ")
    lines.append("    LSR $2233	        ")
    lines.append("    LSR $2233,X	    ")
    lines.append("    NOP	            ")
    lines.append("    ORA #$55	    ")
    lines.append("    ORA $20	        ")
    lines.append("    ORA $20,X	    ")
    lines.append("    ORA $2233	        ")
    lines.append("    ORA $2233,X	    ")
    lines.append("    ORA $2233,Y	    ")
    lines.append("    ORA ($20,X)	    ")
    lines.append("    ORA ($20),Y	    ")
    lines.append("    ORA ($20)	    ")
    lines.append("    PHA	            ")
    lines.append("    PHX	            ")
    lines.append("    PHY	            ")
    lines.append("    PLA	            ")
    lines.append("    PLX	            ")
    lines.append("    PLY	            ")
    lines.append("    ROL A	        ")
    lines.append("    ROL $20	        ")
    lines.append("    ROL $20,X	    ")
    lines.append("    ROL $2233	        ")
    lines.append("    ROL $2233,X	    ")
    lines.append("    ROR A	        ")
    lines.append("    ROR $20	        ")
    lines.append("    ROR $20,X	    ")
    lines.append("    ROR $2233	        ")
    lines.append("    ROR $2233,X	    ")
    lines.append("    RTI	            ")
    lines.append("    RTS	            ")
    lines.append("    SBC #$55	    ")
    lines.append("    SBC $20 	    ")
    lines.append("    SBC $20,X	    ")
    lines.append("    SBC $2233	        ")
    lines.append("    SBC $2233,X	    ")
    lines.append("    SBC $2233,Y	    ")
    lines.append("    SBC ($20,X)	    ")
    lines.append("    SBC ($20),Y	    ")
    lines.append("    SBC ($20)	    ")
    lines.append("    SEC	            ")
    lines.append("    SED	            ")
    lines.append("    SEI	            ")
    lines.append("    STA $20	        ")
    lines.append("    STA $20,X	    ")
    lines.append("    STA $2233	        ")
    lines.append("    STA $2233,X	    ")
    lines.append("    STA $2233,Y	    ")
    lines.append("    STA ($20,X)	    ")
    lines.append("    STA ($20),Y	    ")
    lines.append("    STA ($20)	    ")
    lines.append("    STX $20	        ")
    lines.append("    STX $20,Y	    ")
    lines.append("    STX $2233	        ")
    lines.append("    STY $20	        ")
    lines.append("    STY $20,X	    ")
    lines.append("    STY $2233	        ")
    lines.append("    STZ $20	        ")
    lines.append("    STZ $20,X	    ")
    lines.append("    STZ $2233	        ")
    lines.append("    STZ $2233,X	    ")
    lines.append("    TAX	            ")
    lines.append("    TAY	            ")
    lines.append("    TRB $20	        ")
    lines.append("    TRB $2233	        ")
    lines.append("    TSB $20	        ")
    lines.append("    TSB $2233	        ")
    lines.append("    TSX	            ")
    lines.append("    TXA	            ")
    lines.append("    TXS	            ")
    lines.append("    TYA")
    lines.append("; A remark")
    lines.append("       org $1000")
    lines.append("start: lda #$50")
    lines.append("       sta $5000 ; blah")
    lines.append("       sta $25")
    lines.append("       clc")
    lines.append("       ROR A")
    lines.append("       adc #%10011010")
    lines.append("       sta %0101101000111100")
    lines.append("       sta %00111100")
    lines.append("       lda ($20)")
    lines.append("       adc $10,x")
    lines.append("middle:ldx $20,y")
    lines.append("       adc $3000,x")
    lines.append("       adc $3000,y")
    lines.append("       adc ($40,x) ")
    lines.append("       adc ($40),y")
    lines.append("       nop")
    lines.append("       nop")
    lines.append("label:")
    lines.append("       nop")
    lines.append("       org $3000")
    lines.append("vals:  db @10,$aa,8,$cc,$dd")
    lines.append("       be")
    lines.append("       dw $1020,$3040")
    lines.append("       le")
    lines.append("       dw $1020,$3040")
    lines.append("       ddw $1020,$3040")
    lines.append("       dqw $1020,$3040")
    lines.append("       adc start")
    lines.append("       adc ($40)")
    lines.append("end:   bpl vals")
    lines.append("       db $aa,$bb,$cc,$dd")
    lines.append("       nop")

    a = asm6502(debug=debug)
    (listingtext,symboltext) = a.assemble(lines)

    for line in listingtext:
        print line
    print
    for line in symboltext:
        print line

    a.print_object_code()
go()


    
